info:
  app:
    version: 0.0.1
    name: just anything we wish
    extra: this too
    java:
      version: ${java.version}
  author:
    name: abc

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /anything
  metrics:
    export:
      statsd:
        flavor: datadog
        enabled: false
    enabled: true
    web:
      server:
        auto-time-requests: true
metrics:
  config:
    tag1: anything-i-want

server:
  port: 8090

spring:
# enable us to use   http://localhost:8090/h2-console
  h2:
    console:
        enabled: true
# these elements are just the defaults
  datasource:
    url: jdbc:h2:mem:testdb
    spring.datasource.driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect